name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t housy-backend .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-name: housy-backend
          exit-code: 0
          format: json
          output: trivy-results.json
